### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by MeIsOptical** [DereWah/Skript-GPT#2]
Every time I try to use the "generate a chatgpt completion" effect, it gives me this error.

![image](https://github.com/DereWah/Skript-GPT/assets/88013740/9a4c613a-ed8f-48e1-9aa1-61e5959251d8)

I tried to use different Minecraft versions (1.17, 1.18.2 and 1.19.4) but they all give me the same error. The problem is also not due to plugin compability because I tried removing all the plugins except Skript but it still doesn't work.

**Comment by DereWah** [comment]
> Every time I try to use the "generate a chatgpt completion" effect, it gives me this error.
> 
> ![image](https://github.com/DereWah/Skript-GPT/assets/88013740/9a4c613a-ed8f-48e1-9aa1-61e5959251d8)
> 
> I tried to use different Minecraft versions (1.17, 1.18.2 and 1.19.4) but they all give me the same error. The problem is also not due to plugin compability because I tried removing all the plugins except Skript but it still doesn't work.
> 

Hello there. From the screenshot, it's clear you're receiving an error 429 from the OpenAI API. Read more about it here:
 https://help.openai.com/en/articles/6891829-error-code-429-rate-limit-reached-for-requests

The reasons could be:
Your API key could be expired pr you might be out of credits.

The server you are hosting the server on is blocked by OpenAI's API

**Comment by MeIsOptical** [comment]
Thanks for the help!
